#!/usr/bin/env node
// vim:ft=javascript
//     __                               
//    / /_  _________ _      __________ 
//   / __ \/ ___/ __ \ | /| / / ___/ _ \
//  / /_/ / /  / /_/ / |/ |/ (__  )  __/
// /_.___/_/   \____/|__/|__/____/\___/ 
//                                     
//
var mdns = require('mdns');
var service = process.argv[2] || 'http';
var verbose = process.argv[3] ;
var browser; 

console.log("watching for service:", service);

if (service == 'all'){
  // watch all services
  console.log("here");
  browser = mdns.browseThemAll(); 
} 
else {
  // watch a service 
  browser = mdns.createBrowser(mdns.tcp(service));
}

browser.on('serviceUp', function(service) {
  if (verbose) console.log("up:", service);
  else {
    if (service.txtRecord&&service.txtRecord.name) {
      console.log("up:", service.name, "host:", service.host+":"+service.port, service.txtRecord.name);
    }
    else {
      console.log("up:", service.name, "host:", service.host+":"+service.port);
    }
  }
});
browser.on('serviceDown', function(service) {
  console.log("down:", service);
});

browser.start();
